### PR TITLE
Added cross-build for Scala 2.13

### PR DESCRIPTION
**Pull request by hohonuuli**
I've added a cross-build for Scala 2.13 and upgraded evilplot's dependencies. Everything compiles and tests pass. I'd like to hand the code over to the maintainers to decide what to do with it. Note that jupyter-scala is no longer supported, so I migrated evilplot to use [almond.sh](https://almond.sh/) instead. This is for issue #95

### CODE REVIEW

**Comment by hohonuuli** [comment]
Some of the tests still need to be updated to Scala 2.13. I'll tackle them this weekend.

**Comment by hohonuuli** [comment]
At this point, all tests pass for Scala 2.12 and 2.13.

**Comment by hohonuuli** [comment]
This has been quiet for about a month. Just wondering if anyone is still working on evilplot?

**Comment by hohonuuli** [comment]
Following up again two months after submitting the pull request. Perhaps you're very busy? I'll give it another month, if there's no response, then I'll just fork and publish a 2.13 version on my own. Cheers

**Comment by jkeillor** [comment]
@hohonuuli thanks for the contribution and sorry for the lack of response. We have not been working actively on evilplot recently and this slipped through the cracks. I will take a look at your changes and work on getting the cross-builds published over the next couple days.

**Comment by hohonuuli** [comment]
@jkeillor Thanks for responding and I hope you find the changes helpful. I wasn't intending to pressure you, but open source being open source, sometimes projects are quietly abandoned. Really appreciate this project and I've been finding it very useful! Stay well.

**Pull request merged**
