### PR TITLE
Filling path renderers

### PR DESCRIPTION
**Pull request by chrisshafer**
### DEPENDS ON https://github.com/cibotech/evilplot/pull/78 merge that first

- Adds path renderers to support area plots
- Adds additional helpers to cartesian plot
- Adds interaction utils to path renderers
- [BUG] Fixes data composers manipulate function to return composer

evilplothoveredribbon

### CODE REVIEW

**Comment by chrisshafer** [comment]
screen shot 2018-12-01 at 9 47 39 pm
screen shot 2018-12-01 at 9 47 33 pm

**Comment by johndavidhahn** [comment]
@chrisshafer can you bump this to see if we can get CI to pick it up.  Not sure what travis's problem is.

**Comment by chrisshafer** [comment]
@johndavidhahn Sure thing! It doesn't look like there has been any activity in the last 26 days in the build history https://travis-ci.org/cibotech/evilplot/builds ? But it does show a current build passed as of yesterday https://travis-ci.org/cibotech/evilplot, which is weird.  May want to check the configuration ?

**Comment by johndavidhahn** [comment]
@chrisshafer, the Joe helped me fix things with Travis, good old remove and re-add.  Try bumping again.

**Comment by johndavidhahn** [comment]
If you have no other changes, I'll merge this tomorrow, @chrisshafer

**Comment by chrisshafer** [comment]
@johndavidhahn no more changes, thanks!

**Pull request merged**
